feat: detail-header-component 구현
wwweric12/capstone-design1 pull request #14
Opened 2024-04-13 08:36 UTC by wwweric12

- detail-header-component 구현했습니다.

2024-04-15 06:53 UTC, ndaemy requested changes
svg 가 inline 이 아닌게 아쉬워서 reject 해둬여
급하면 머지하고 나중에 픽스 고고

2024-04-15 06:53 UTC, ndaemy commented on src/assets/images/prev.svg
이거 보통 chevron 이라고 불러영

2024-04-15 06:53 UTC, ndaemy commented on src/components/atoms/Logo.tsx
오 이거 svg 로 로고파일 만들지 않고 그냥 이렇게?

2024-04-15 06:53 UTC, ndaemy commented on src/components/molecules/DetailHeader.tsx
> +        <PrevImg src={prevSvg} />
svg 는 img 태그로 감싸지 말아주세여
img 태그는 추가적인 http 요청을 보내야 하기 때문에 불필요한 오버헤드가 생깁니다
as ReactComponent 를 사용하는 방법도 있고, svgr 같은걸 쓰는 방법도 있어여 리서치 고고

2024-04-15 06:53 UTC, ndaemy commented on src/stories/MainHeader.stories.ts
> +  title: 'Components/atoms',
얘는 atoms 가 아니지 않아..?

2024-04-15 06:53 UTC, ndaemy commented on src/stories/DetaiHeader.stories.ts
> +  args: {
요기에 name: 'Header' 를 추가하면 불필요하게 패키지를 안 만들 수도 있어

2024-04-15 09:39 UTC, wwweric12 commented on src/stories/MainHeader.stories.ts
> +  title: 'Components/atoms',
엇 ,,얘가 왜,, 여기에,,,

2024-04-15 09:40 UTC, wwweric12 commented on src/components/atoms/Logo.tsx
로고가 아직 정해진게 아니여서 일단은 이렇게 진행했습니다!

2024-04-15 11:44 UTC, wwweric12 commented on src/components/molecules/DetailHeader.tsx
> +        <PrevImg src={prevSvg} />
일단은 ReactComponent로 고치고 이후에 알려주신 방법으로 한번 해보겠습니다.

2024-04-15 12:15 UTC, merged

2024-04-24 05:26 UTC, ndaemy reviewed
굿

2024-04-24 05:26 UTC, ndaemy commented on src/components/molecules/DetailHeader.tsx
> +`;
PrevButton 에 gap 속성을 주는것도 방법