feat: footer-button-component 구현
wwweric12/capstone-design1 pull request #15
Opened 2024-04-14 10:33 UTC by wwweric12

- footer에 들어갈 button도 구현했습니다.
  - svg를 여러개를 하나의 tag에서 isClicked가 되었을때 color를 변경하려고 합니다
     어떠한 방법이 좋은 방법인지 몰라서 다음과같이 여러개의 component로 구성하였습니다.

2024-04-15 07:26 UTC, ndaemy requested changes
svg 관련 이슈때매 reject 인데, 나중에 리팩토링 해도 무방!

2024-04-15 07:26 UTC, ndaemy commented on src/components/atoms/FooterButton.tsx
> +  );
요긴 구두로 설명한대로 바꿔보는 것으로!

2024-04-15 07:26 UTC, ndaemy commented on src/components/organisms/Footer.tsx
> +  const footer: FooterButtonProps[] = [
1. naming 이 footerButtons 정도가 되면 더 확 와닿는 naming 일듯?
2. 이거 나중엔 props 로 받아야되는거지?

2024-04-15 07:26 UTC, ndaemy commented on src/components/organisms/Footer.tsx
> +          key={i}
차라리 key 를 item.type 으로 해보는건? item.type 이 unique 한 필드가 맞다면 그게 나을듯!

2024-04-15 07:26 UTC, ndaemy commented on src/stories/Footer.stories.ts
> +import ft from '../components/organisms/Footer';
의도가 딱히 있는게 아니라면 "React Component 는 PascalCase 로 네이밍한다" 라는 convention 을 깨지 않는게 좋아
나중에 다시 코드 볼 때 이게 리액트 컴퍼넌트인지 아닌지 두 번 생각해야 하니까

2024-04-15 12:21 UTC, wwweric12 commented on src/components/organisms/Footer.tsx
> +  const footer: FooterButtonProps[] = [
1. 아하 좋은거 같습니다. 
2. type이랑 text는 props로 안받고 추후에는 아무래도 주소값에 따라 color가 결정되어야 되기때문에 그런 부분들을 props로 받으려고했습니다.

2024-04-15 12:22 UTC, wwweric12 commented on src/components/organisms/Footer.tsx
> +          key={i}
key가 마땅히 떠오르지가 않아서 일단 index로 했는데 좋은 방법인거 같습니다!

2024-04-15 12:22 UTC, wwweric12 commented on src/stories/Footer.stories.ts
> +import ft from '../components/organisms/Footer';
storybook에서 name이 겹치면 안되가지고 방법이 없을까 했는데 
name 설정이 따로 있어서 고치겠습니다!

2024-04-16 07:30 UTC, merged

2024-04-24 05:29 UTC, ndaemy reviewed
굿굿